apiVersion: v1
kind: ConfigMap
metadata:
  name: mysql-config
data:
  mysql-url: jdbc:mysql://localhost:3306/lportal?useUnicode=true&characterEncoding=UTF-8&useFastDateParsing=false
  mysql-driver: com.mysql.cj.jdbc.Driver