apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-conf
data:
  nginx.conf: |

    events {
      worker_connections  10240;
    }
    http {
      auth_basic "Auth required";
      auth_basic_user_file /etc/nginx/.htpasswd;

      upstream tomcatservers { 
        server liferay:8080; 
      }   
      server {
        listen 80;
        location / {
          proxy_pass         http://tomcatservers;
          proxy_redirect     off;
          proxy_set_header   Host $host;
          proxy_set_header   X-Real-IP $remote_addr;
          proxy_set_header   X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header   X-Forwarded-Host $server_name;
          }
      }
    }

---
apiVersion: v1
kind: ConfigMap
metadata:
  name: basicauth
  data:
    htpasswd: |
     adminuser:$apr1$19ujva4z$Wvo749.DAMSYH8ZthapvB0


---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  type: NodePort
  ports:
  - port: 80
    targetPort: 80
    nodePort: 30081
  selector:
    app: nginx

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-nginx
spec:
  selector:
    matchLabels:
      run: my-nginx
  replicas: 1
  template:
    metadata:
      labels:
        run: my-nginx
    spec:
      containers:
      - name: nginx
        image: nginx:1.16.0-alpine
        ports:
        - containerPort: 80
        volumeMounts:
        - mountPath: /etc/nginx/conf.d
          name: configmap-volume
        - mountPath: /etc/nginx/.htpasswd
          name: configmap-auth
      volumes:
      - name: configmap-volume
        configMap:
          name:  nginx-conf
      - name: configmap-auth
        configMap:
          name:  basicauth
     